### ISSUE TITLE
How do I run source separation on a different video?

### ISSUE THREAD

**Issue by jayavanth** [andrewowens/multisensory#2]
I get this when I run it on my video:
```
Writing to: ../results/
Traceback (most recent call last):
  File "sep_video.py", line 442, in <module>
    ut.make_video(full_ims, pr.fps, pj(arg.out, 'fg%s.mp4' % name), snd(full_samples_fg))
  File "~/multisensory/src/aolib/util.py", line 3156, in make_video
    write_ims = (type(im_fnames[0]) != type(''))
IndexError: list index out of range
```
Do I have to run something else before `sep_video.py`?

**Comment by jayavanth** [comment]
Nvm. My video was corrupted!

**Comment by andrewowens** [comment]
Thanks, I'll add a better error message for this in the future.
