### ISSUE TITLE
file input for blind audio source separation

### ISSUE THREAD

**Issue by prashantmaheshwari94** [andrewowens/multisensory#20]
Thanks for the amazing implementation and pre-trained models.

I want to use this for blind audio source separation for audio files only. but it gives me the following error.
ffmpeg -loglevel error -ss 0.0 -i "../../pyAudioAnalysis/90131M02_.wav" -safe 0  -t 8.338 -r 29.97 -vf scale=256:256 "/var/folders/kh/2zcggyvx7gs6l10p8pq7jkgw_0bxjx/T/tmpKTCMbU/small_%04d.png"
Output file #0 does not contain any stream
Traceback (most recent call last):
  File "sep_video.py", line 398, in <module>
    ret = run(arg.vid_file, t, arg.clip_dur, pr, gpus[0], mask = arg.mask, arg = arg, net = net)
  File "sep_video.py", line 254, in run
    'ffmpeg -loglevel error -ss %(start_time)s -i "%(vid_file)s" -safe 0  '
  File "/Volumes/workspace/multisensory/src/aolib/util.py", line 915, in sys_check
    fail('Command failed! %s' % cmd)
  File "/Volumes/workspace/multisensory/src/aolib/util.py", line 12, in fail
    def fail(s = ''): raise RuntimeError(s)
RuntimeError: Command failed! ffmpeg -loglevel error -ss 0.0 -i "../../pyAudioAnalysis/90131M02_.wav" -safe 0  -t 8.338 -r 29.97 -vf scale=256:256 "/var/folders/kh/2zcggyvx7gs6l10p8pq7jkgw_0bxjx/T/tmpKTCMbU/small_%04d.png"

What is the correct format to run it for audio files?

Cheers!

**Comment by fanglixuezi** [comment]
> Thanks for the amazing implementation and pre-trained models.
> 
> I want to use this for blind audio source separation for audio files only. but it gives me the following error.
> ffmpeg -loglevel error -ss 0.0 -i "../../pyAudioAnalysis/90131M02_.wav" -safe 0 -t 8.338 -r 29.97 -vf scale=256:256 "/var/folders/kh/2zcggyvx7gs6l10p8pq7jkgw_0bxjx/T/tmpKTCMbU/small_%04d.png"
> Output file #0 does not contain any stream
> Traceback (most recent call last):
> File "sep_video.py", line 398, in
> ret = run(arg.vid_file, t, arg.clip_dur, pr, gpus[0], mask = arg.mask, arg = arg, net = net)
> File "sep_video.py", line 254, in run
> 'ffmpeg -loglevel error -ss %(start_time)s -i "%(vid_file)s" -safe 0 '
> File "/Volumes/workspace/multisensory/src/aolib/util.py", line 915, in sys_check
> fail('Command failed! %s' % cmd)
> File "/Volumes/workspace/multisensory/src/aolib/util.py", line 12, in fail
> def fail(s = ''): raise RuntimeError(s)
> RuntimeError: Command failed! ffmpeg -loglevel error -ss 0.0 -i "../../pyAudioAnalysis/90131M02_.wav" -safe 0 -t 8.338 -r 29.97 -vf scale=256:256 "/var/folders/kh/2zcggyvx7gs6l10p8pq7jkgw_0bxjx/T/tmpKTCMbU/small_%04d.png"
> 
> What is the correct format to run it for audio files?
> 
> Cheers!

I met the same error "RuntimeError: Command failed! ffmpeg -loglevel error -ss 0.0 -i ".Did u solved? Thanks~
