### ISSUE TITLE
make_video_helper() missing 3 required positional arguments: 'x', 'in_dir', and 'tmp_ext'

### ISSUE THREAD

**Issue by Lugangz** [andrewowens/multisensory#8]
When I run the code, and I got something wrong, how to solve(Ubuntu, tensorflow-gpu1.8)
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
TypeError: make_video_helper() missing 3 required positional arguments: 'x', 'in_dir', and 'tmp_ext'
"""
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/george/multisensory/src/sep_video.py", line 450, in <module>
    ig.show(table)
  File "/media/george/multisensory/src/aolib/img.py", line 13, in show
    return imtable.show(*args, **kwargs)
  File "/media/george/multisensory/src/aolib/imtable.py", line 72, in show_table
    html_rows = html_from_rows(table, output_dir)
  File "/media/george/multisensory/src/aolib/imtable.py", line 413, in html_from_rows
    html_rows.append("<td>" + "<td>".join(html_from_cell(x, output_dir) for x in row))
  File "/media/george/multisensory/src/aolib/imtable.py", line 413, in <genexpr>
    html_rows.append("<td>" + "<td>".join(html_from_cell(x, output_dir) for x in row))
  File "/media/george/studyProjects/multisensory/src/aolib/imtable.py", line 308, in html_from_cell
    return x.make_html(output_dir)
  File "/media/george/studyProjects/multisensory/src/aolib/imtable.py", line 587, in make_html
    make_video(fname, self.ims, self.fps, sound = self.sound)
  File "/media/george/studyProjects/multisensory/src/aolib/imtable.py", line 498, in make_video
    [(i, x, in_dir, tmp_ext) for i, x in enumerate(ims)])
  File "/media/george/multisensory/src/aolib/util.py", line 2726, in parmap
    ret = pool.map_async(f, xs).get(10000000)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
TypeError: make_video_helper() missing 3 required positional arguments: 'x', 'in_dir', and 'tmp_ext'

**Comment by chouqin3** [comment]
It can be solved by adding subscript, e.g. xs[0],xs[1]...
